apiVersion: v1
kind: Service
metadata:
  name: deis-builder
  labels:
    heritage: deis
    release: 2.0.0
spec:
  ports:
    - port: 2222
      targetPort: 2223
      name: ssh
      protocol: TCP
    - port: 3000
      name: fetcher
      protocol: TCP
  selector:
    app: deis-builder
